#!/usr/bin/env bash
# add iptables rules to drop all IP traffic from countries in block list
#   block list: /etc/xt_geoip-block_countries
#
# see: https://github.com/katmore/xt_geoip-block_countries
# @author D. Bird <retran@gmail.com>

set -o pipefail

[ -n "$BLOCK_COUNTRIES_CONFIG" ] || BLOCK_COUNTRIES_CONFIG=/etc/xt_geoip-block_countries

echo "block countries config: $BLOCK_COUNTRIES_CONFIG"

( [ -f "$BLOCK_COUNTRIES_CONFIG" ] && [ -r "$BLOCK_COUNTRIES_CONFIG" ] ) || {
	>&2 echo "cannot access block countries config: $BLOCK_COUNTRIES_CONFIG"
	exit 1
}

while read cc; do
	echo "DROP incoming traffic from '$cc'"
	iptables -I INPUT -m geoip --src-cc $cc -j DROP || exit
done < <(cut -d "#" -f1 "$BLOCK_COUNTRIES_CONFIG" | grep -v "^$")


