#!/usr/bin/env bash
# updates xt_geoip database if it is older than 1 week old
# 
# see: https://github.com/katmore/xt_geoip-block-countries
# @author D. Bird <retran@gmail.com>

[ -d /usr/share/xt_geoip ] || {
	mkdir -p /usr/share/xt_geoip || exit
}

cd /usr/share/xt_geoip || exit

echo 'download and format GeoIP data: in progress (this may take a while)'

/usr/local/lib/xt_geoip-block_countries/xt_geoip_dl-convert2legacy || exit

echo 'download and format GeoIP data: complete'

/usr/lib/xtables-addons/xt_geoip_build -D /usr/share/xt_geoip /usr/share/xt_geoip/GeoIPCountryWhois.csv
