#!/usr/bin/env bash
# xt_geoip-block_countries
# applies iptables rules to DROP all IP traffic from each country in the block countries config
#
# usage:
#   xt_geoip-block_countries
#
# environment variables:
#   BLOCK_COUNTRIES_CONFIG : path to block countries config file (country block list)
#     default value: /etc/xt_geoip-block_countries
#
# see: https://github.com/katmore/xt_geoip-block_countries
# author: D. Bird <retran@gmail.com>
# (c) 2019 Doug Bird. All Rights Reserved.
# Distributed under the terms of the MIT license or the GPLv3 license.
# This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com
# The GeoLite2 databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License.

set -o pipefail

[ -n "$BLOCK_COUNTRIES_CONFIG" ] || BLOCK_COUNTRIES_CONFIG=/etc/xt_geoip-block_countries

# FUNCTION: help
#   outputs reflective "help" message using comments from top of this script file
help() {
  local l=
  while read -r l; do
    [ "${l:0:1}" = "#" ] || break
    l=${l:1}
    [ -n "${l//[[:blank:]]/}" ] || l=""
    [ "${l:0:1}" != " " ] || l=${l:1}
    echo "$l"
  done < <(tail -n +2 "${BASH_SOURCE[0]}")
}

# parse options
while getopts huav-: o; do
  case "$o" in
    h|u|a|v) help; exit;;
    -)
    case "$OPTARG" in
      help|usage|about|version) help; exit;;
      '') break;;
    esac
    ;;
  esac
done
shift $((OPTIND-1))

echo "block countries config: $BLOCK_COUNTRIES_CONFIG"

( [ -f "$BLOCK_COUNTRIES_CONFIG" ] && [ -r "$BLOCK_COUNTRIES_CONFIG" ] ) || {
	>&2 echo "cannot access block countries config: $BLOCK_COUNTRIES_CONFIG"
	exit 1
}

while read cc; do
	echo "DROP incoming traffic from '$cc'"
	iptables -I INPUT -m geoip --src-cc $cc -j DROP || exit
done < <(cut -d "#" -f1 "$BLOCK_COUNTRIES_CONFIG" | grep -v "^$")


